version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin      # Access Key
      MINIO_ROOT_PASSWORD: minioadminpassword  # Secret Key
    volumes:
      - ./data:/data                   # Maps storage on your local machine
    ports:
      - "9000:9000"                    # Port for MinIO API
      - "9001:9001"                    # Port for the admin console
    restart: always                    # Automatically restart the container.
    command: server /data --address ":9000" --console-address ":9001"