version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin      # Clave de acceso (Access Key)
      MINIO_ROOT_PASSWORD: minioadminpassword  # Clave secreta (Secret Key)
    volumes:
      - ./data:/data                   # Mapea el almacenamiento en tu máquina local
    ports:
      - "9000:9000"                    # Puerto para la API de MinIO
      - "9001:9001"                    # Puerto para la consola de administración
    restart: always                    # Reiniciar el contenedor automáticamente
    command: server /data --console-address ":9001"